title: Sam Roughley
theme: jekyll-theme-minimal

header_pages:
- about.md
- projects.md

url: "https://samroughley.github.io"

#logo: "https://media.licdn.com/dms/image/v2/D4D03AQHGs5fB91Ss2g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1701198486833?e=1750896000&v=beta&t=1voJ9JSafTaH1EtqiU31-XIPvaP6F1-N0KVgty00lfI"
